/**
 * Activity tracking (CLAUDE.md §11).
 *
 * Privacy (CLAUDE.md §9): Jambu records how long the user has been working,
 * not what they are working on. Only the registrable domain is ever stored —
 * never a path, query string or page title.
 */

import type { IsoTimestamp } from './time.js';

/**
 * Whether the user is currently at the keyboard.
 *
 * `unknown` is not a synonym for `idle`: it means Jambu has no recent signal
 * at all, such as immediately after install. A closed browser counts as
 * `idle`. See docs/ARCHITECTURE.md §6.
 */
export type ActivityStatus = 'active' | 'idle' | 'unknown';

/**
 * An aggregated slice of work (CLAUDE.md §11).
 *
 * Aggregated deliberately: CLAUDE.md §9 prefers whole sessions over raw event
 * streams.
 */
export interface ActivitySession {
  readonly startedAt: IsoTimestamp;
  readonly endedAt: IsoTimestamp;
  readonly activeSeconds: number;
  /** Registrable domain only, e.g. `notion.so`. Never a full URL. */
  readonly domain?: string;
}

/**
 * A session as submitted by the extension.
 *
 * `clientSessionId` is generated by the extension and makes ingestion
 * idempotent: CLAUDE.md §26 requires the extension to buffer and retry when
 * the API is unavailable, and without this key a replayed batch would create
 * duplicate rows and inflate continuous-work totals.
 */
export interface ActivitySessionInput extends ActivitySession {
  readonly clientSessionId: string;
}
